//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace PimsApp
{
    public partial class Home
    {
        // Comment: Using nullable reference types for better null handling
        #nullable enable

        /// <summary>
        /// form1 control.
        /// </summary>
        protected HtmlForm? Form { get; set; } // Modernized: Renamed to follow C# naming conventions and made nullable

        /// <summary>
        /// lblWelcome control.
        /// </summary>
        protected Label? WelcomeLabel { get; set; } // Modernized: Renamed to follow C# naming conventions and made nullable

        /// <summary>
        /// btnLogout control.
        /// </summary>
        protected Button? LogoutButton { get; set; } // Modernized: Renamed to follow C# naming conventions and made nullable

        /// <summary>
        /// pageTitle control.
        /// </summary>
        protected HtmlGenericControl? PageTitle { get; set; } // Modernized: Renamed to follow C# naming conventions and made nullable

        /// <summary>
        /// lblSucessMessage control.
        /// </summary>
        protected Label? SuccessMessageLabel { get; set; } // Modernized: Renamed to follow C# naming conventions, fixed typo, and made nullable

        /// <summary>
        /// btnRegisterComplaint control.
        /// </summary>
        protected Button? RegisterComplaintButton { get; set; } // Modernized: Renamed to follow C# naming conventions and made nullable

        /// <summary>
        /// gvComplaints control.
        /// </summary>
        protected GridView? ComplaintsGridView { get; set; } // Modernized: Renamed to follow C# naming conventions and made nullable

        #nullable restore
    }
}