// This file is automatically generated. Manual changes may be overwritten.

namespace PimsApp
{
    public partial class Home
    {
        // Use 'protected' instead of 'protected global' for better encapsulation
        // Comment: Changed access modifier to improve encapsulation
        protected System.Web.UI.HtmlControls.HtmlForm form1;

        // Use 'Label' instead of 'System.Web.UI.WebControls.Label' for brevity
        // Comment: Simplified type declaration
        protected Label lblWelcome;

        // Use 'Button' instead of 'System.Web.UI.WebControls.Button' for brevity
        // Comment: Simplified type declaration
        protected Button btnLogout;

        // Use 'HtmlGenericControl' instead of 'System.Web.UI.HtmlControls.HtmlGenericControl' for brevity
        // Comment: Simplified type declaration
        protected HtmlGenericControl pageTitle;

        // Fixed typo in variable name (Sucess -> Success)
        // Comment: Corrected spelling in variable name
        protected Label lblSuccessMessage;

        protected Button btnRegisterComplaint;

        // Use 'GridView' instead of 'System.Web.UI.WebControls.GridView' for brevity
        // Comment: Simplified type declaration
        protected GridView gvComplaints;

        // Comment: Consider adding data annotations for security and validation
        // [Required]
        // [StringLength(100, MinimumLength = 3)]
        // public string SomeProperty { get; set; }

        // Comment: Consider implementing IDisposable if dealing with unmanaged resources
        // public void Dispose()
        // {
        //     // Dispose of unmanaged resources here
        // }
    }
}